FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.su[m] ./
RUN go mod download

COPY . .
RUN go build -o /bin/cliente ./cmd/cliente

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /bin/cliente .
CMD ["./cliente"]
